params:
  num_image_pairs: 25
  num_matches_per_image_pair: 100

networks:
  baymax:
    path_to_network_params: code/data_volume/pdc/trained_models/single_objects/baymax_stable_3/003500.pth

  headphones:
    path_to_network_params: code/data_volume/pdc/trained_models/single_objects/headphones_3/003500.pth

dataset: [] # which dataset to use, not used for now

output_dir: code/data_volume/pdc/analysis
