params:
  num_image_pairs: 25
  num_matches_per_image_pair: 100


networks:
  6e-5_lr:
    path_to_network_params: code/data_volume/trained_models/6e-5_lr/030000.pth
    descriptor_dimension: 3
    image_width: 640
    image_height: 480
  3e-5_lr:
    path_to_network_params: code/data_volume/trained_models/3e-5_lr/003500.pth
    descriptor_dimension: 3
    image_width: 640
    image_height: 480
  1e-5_lr:
    path_to_network_params: code/data_volume/trained_models/1e-5_lr/002000.pth
    descriptor_dimension: 3
    image_width: 640
    image_height: 480
  1e-6_lr:
    path_to_network_params: code/data_volume/trained_models/1e-6_lr/002000.pth
    descriptor_dimension: 3
    image_width: 640
    image_height: 480
  10_scenes_drill_no_masked_non_matches:
    path_to_network_params: code/data_volume/trained_models/no_masked_non_matches/003500.pth
    descriptor_dimension: 3
    image_width: 640
    image_height: 480
  10_scenes_drill_masked_non_matches:
    path_to_network_params: code/data_volume/trained_models/masked_non_matches/003500.pth
    descriptor_dimension: 3
    image_width: 640
    image_height: 480



dataset: [] # which dataset to use, not used for now

output_dir: code/data_volume/pdc/analysis
