training:
  learning_rate: 1.0e-4
  learning_rate_decay: 0.9
  steps_between_learning_rate_decay: 500 # decay the learning rate after this many steps
  weight_decay: 1.0e-4
  num_iterations: 3500 # number of iterations to train for
  logging_rate: 10 # how often to print out
  save_rate: 500 # how often to save the network
  num_workers: 10 # num threads/workers for dataset loading
  batch_size: 1
  loss_function: pixelwise_contrastive_loss # not currently used
  logging_dir: code/data_volume/trained_models # where to store trained models
  logging_dir_name: test # overwrites if this is here

dense_correspondence_network:
  descriptor_dimension: 3
  image_width: 640
  image_height: 480

