networks:
  10_scenes_drill:
    path_to_network_params: /home/manuelli/code/dense_correspondence/recipes/trained_models/10_drill_long_3d/dense_resnet_34_8s_03505.pth
    descriptor_dimension: 3
    image_width: 640
    image_height: 480
