qlogs_root_path: code/data_volume/pdc/logs_proto
object_id: "baymax"
train:
- "2018-04-24-17-16-40" # head pointed down left
- "2018-04-24-17-34-46" # head pointed down
- "2018-04-24-17-38-19" # head pointed up and right
test:
- "2018-04-24-17-42-27" # head pointed up and right
- "2018-04-24-17-30-08" # head pointed down
evaluation_labeled_data_path: []
