logs_root_path: code/data_volume/pdc/logs_proto
object_id: "hat_mit_black"
train:
- "2018-04-25-21-19-47" # pointing down
test:
- "2018-04-25-21-19-47" # pointing down
evaluation_labeled_data_path: 
- "nowhereyet"
