logs_root_path: code/data_volume/pdc/logs_proto
object_id: "star_bot"
train:
- "2018-05-04-19-42-34" # head away from robot
- "2018-05-04-20-04-43" # head towards robot
test:
- "2018-05-04-20-08-47" # head pointing right and forwards
- "2018-05-07-18-38-43" # head towards robot
- "2018-05-07-18-46-43" # head pointing left
evaluation_labeled_data_path: 
- "nowhereyet"